version: '3.8'
services:
  builder:
    build:
      context: .
      dockerfile: ./docker/builder/Dockerfile
    volumes:
      - ./:/builder
  nginx:
    image: nginx:1.21-alpine
    ports:
      - '8080:80'
    volumes:
      - ./docker/nginx/defaul.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - builder
  horizon:
    build:
      context: .
      dockerfile: ./docker/horizon/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/horizon/supervisor.conf:/etc/supervisor/conf.d/horizon.conf
      - ./docker/horizon/supervisor.conf:/etc/supervisord.conf
    depends_on:
      - nginx
      - redis
      - mariadb
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - nginx
      - horizon
  mariadb:
    image: 'mariadb:10'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'dbdata:/var/lib/mysql'
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redisdata:/data'
volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
